Repository RedHatInsights/insights-api-common-rails, pull requests merged in 2019-10, with the labels that each got.

#119 Prevent first pages from having a "prev" page link
  lib/manageiq/api/common/paginated_response.rb
  spec/lib/manageiq/api/common/paginated_response_spec.rb
Labels: bug

#123 Adding support for case insensitive searches.
  README.md
  lib/manageiq/api/common/filter.rb
  spec/dummy/app/controllers/api/v1/mixins/index_mixin.rb
  spec/dummy/app/controllers/api/v1/sources_controller.rb
  spec/dummy/app/controllers/api/v1x0.rb
  spec/dummy/config/routes.rb
  spec/requests/api/v1.0/filter_spec.rb
Labels: enhancement

#117 Add 404 "not found" to generated responses
  lib/manageiq/api/common/open_api/generator.rb
Labels: bug

#124 Update to openapi_parser v0.6.1
  manageiq-api-common.gemspec
  spec/requests/request_body_validation_spec.rb
Labels: bug, enhancement

#129 Fix nested attributes
  lib/manageiq/api/common/open_api/docs/object_definition.rb
  spec/dummy/public/doc/openapi-3-v1.0.0.json
  spec/requests/params_spec.rb
Labels: bug

#125 Fix error responses for filtering
  lib/manageiq/api/common/filter.rb
Labels: bug
