Repository RedHatInsights/insights-api-common-rails, pull requests merged in 2019-09, with the labels that each got.

#90 Adding support for an optional base_query
  lib/manageiq/api/common/graphql/generator.rb
  lib/manageiq/api/common/graphql/templates/query_type.erb
Labels: enhancement

#96 Deduplicate openapi generator
  lib/manageiq/api/common/open_api/generator.rb
Labels: enhancement

#97 Validate IDs when provided in the request path
  lib/manageiq/api/common/application_controller_mixins/api_doc.rb
  lib/manageiq/api/common/application_controller_mixins/request_path.rb
  spec/dummy/app/controllers/api/v1x0.rb
  spec/dummy/config/routes.rb
  spec/dummy/public/doc/openapi-3-v1.0.0.json
  spec/lib/manageiq/api/common/application_controller_mixins/request_path_spec.rb
  spec/requests/request_path_spec.rb
Labels: bug

#100 Default to add ':as => :json' for all patch, post, and put request specs
  spec/requests/request_body_validation_spec.rb
  spec/support/default_as_json.rb
  spec/support/requests_spec_helper.rb
Labels: enhancement

#91 Enabling specs in travis
  .travis.yml
  bin/setup
  spec/dummy/app/controllers/api/graphql_controller.rb
  spec/dummy/app/controllers/api/v1/graphql_controller.rb
  spec/dummy/app/controllers/api/v1x0.rb
  spec/dummy/bin/setup
  spec/dummy/db/migrate/20190923115700_add_db_schema.rb
  spec/dummy/public/doc/openapi-3-v1.0.0.json
  spec/requests/api/graphql_spec.rb
  spec/requests/params_spec.rb
Labels: unmergeable
